"""Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added."""

s = "abcb"
t = "abcbe"

dic = {}
for i in s:
    if i not in dic:
        dic[i] = 1
    else:
        dic[i] += 1
dic_t = {}
for j in t:
    if j not in dic_t:
        dic_t[j] = 1
    else:
        dic_t[j] += 1


for i in dic_t:
    if i not in dic:
        print(i)
    elif dic[i] != dic_t[i]:
        print(i)






